version: "3"
services: 
    www:
        build: .
        restart: always
        ports: 
            - '8003:80'
        volumes: 
            -  ./:/var/www/public/
        networks:
            - default
    db:
        image: mysql:8.0.23
        restart: always
        ports: 
            - '3307:3307'
        environment: 
            MYSQL_DATABASE: meudb
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            
volumes: 
    db_data: